global.sha256 = require('sha256')

require('./checkingMethods')
require('./errorMethods')
require('./stringMethods')
require('./urlMethods')
require('./Waiter')
require('./classCollecting')
require('./objectMethods')
require('./configMethods')
require('./styleMethods')
require('./vueMethods')
require('./helperMethods')
require('./facebookMethods')
